"use strict";

const flowsDefault = require("./guidedFlowService");
const approvalDefault = require("./linkApprovalService");
const resolverDefault = require("./inputResolverService");
const identitiesDefault = require("./identityService");

function createLinkApprovalFlowService(options = {}) {
  const flows = options.guidedFlowService || flowsDefault, approval = options.linkApprovalService || approvalDefault, resolver = options.inputResolverService || resolverDefault, identities = options.identityService || identitiesDefault;
  const args = context => [context.platform || "whatsapp", context.groupId, context.userId];
  const reply = (context, text) => context.replyText(String(text));
  const typeName = value => ({ youtube: "YouTube", whatsapp: "WhatsApp", telegram: "Telegram", discord: "Discord", pokemon_go: "Pokémon GO", google_drive: "Google Drive", campfire: "Campfire", shortened: "Encurtador" }[value] || "Outro");
  async function replaceOwn(context, input) { const existing = await flows.getActiveFlow(...args(context)); if (existing && !String(existing.flowId).startsWith("link_approval")) return { conflict: true }; if (existing) await flows.cancelFlow(...args(context)); return flows.startFlow(input); }
  async function resolveAccess(context, groupId, userId) { const chat = await context.client.getChatById(groupId); const botId = identities.normalizeUserId(context.client.info?.wid), participant = id => chat.participants?.find(item => identities.identitiesMatch(item.id, id)); return { chat, userPresent: Boolean(participant(userId)), botPresent: Boolean(participant(botId)), participant: participant(userId), botParticipant: participant(botId) }; }
  function groupMenu(groups) { return `🔗 ESCOLHA O GRUPO\n\n${groups.map((group, index) => `${index + 1}️⃣ ${group.name}`).join("\n")}\n\n0️⃣ Cancelar`; }
  function review(data) { return `🔗 REVISAR SOLICITAÇÃO\n\nGrupo:\n${data.groupName}\n\nDomínio:\n${data.link.domain}\n\nTipo:\n${typeName(data.link.linkType)}\n\nDescrição:\n${data.description || "Não informada"}${data.whitelisted ? "\n\n✅ Domínio reconhecido como permitido, mas ainda depende de aprovação da moderação." : ""}\n\n1️⃣ Enviar para análise\n2️⃣ Editar grupo\n3️⃣ Editar descrição\n4️⃣ Cancelar`; }
  async function startRequest(context, url, initialMessageId = null) {
    let link; try { link = approval.validateLinkRequest(url); } catch (error) { await reply(context, `❌ ${error.message}`); return { status: "invalid", error }; }
    const groups = await approval.getEligibleGroupsForLinkRequest({ requesterId: context.userId, resolveAccess: (groupId, userId) => resolveAccess(context, groupId, userId) });
    if (!groups.length) { await reply(context, "⚠️ Não encontrei nenhum grupo disponível para solicitação de link."); return { status: "no_groups" }; }
    const data = { link, groups: groups.map(group => ({ groupId: group.groupId, name: group.name })), initialMessageId };
    const started = await replaceOwn(context, { flowId: "link_approval_request", platform: context.platform || "whatsapp", conversationId: context.groupId, userId: context.userId, step: "choose_group", data });
    if (started.conflict) { await reply(context, "⚠️ Conclua ou cancele o fluxo atual antes de solicitar outro link."); return { status: "conflict" }; }
    await reply(context, groupMenu(data.groups)); return { status: "started" };
  }
  async function startCancel(context, request) { await replaceOwn(context, { flowId: "link_approval_cancel", platform: context.platform || "whatsapp", conversationId: context.groupId, userId: context.userId, step: "confirm_cancel", data: { requestId: request.requestId } }); await reply(context, `⚠️ Cancelar a solicitação ${request.requestId}?\n\n1️⃣ Confirmar\n2️⃣ Cancelar`); }
  async function startReview(context, request, role, names = {}) { await replaceOwn(context, { flowId: "link_approval_review", platform: context.platform || "whatsapp", conversationId: context.groupId, userId: context.userId, step: "review_action", data: { requestId: request.requestId, role, names } }); await reply(context, `🔗 ANALISAR LINK\n\nProtocolo: ${request.requestId}\nSolicitante: ${names.requesterName || "Membro não identificado"}\nGrupo: ${names.groupName || "Grupo"}\nDomínio: ${request.domain}\nTipo: ${typeName(request.linkType)}\nDescrição: ${request.description || "Não informada"}\nURL sanitizada: ${request.sanitizedUrl}\nStatus: Pendente\n\n1️⃣ Aprovar e publicar\n2️⃣ Rejeitar\n3️⃣ Cancelar análise`); }
  async function hasActiveFlow(context) { if (!context?.groupId || !context?.userId) return false; const session = await flows.getActiveFlow(...args(context)); return String(session?.flowId || "").startsWith("link_approval"); }
  async function cancel(context, message = "❌ Operação cancelada.") { await flows.cancelFlow(...args(context)); await reply(context, message); return { status: "cancelled" }; }
  async function handleRequest(context, session, text) {
    const nav = resolver.resolveNavigation(text); if (["cancel", "menu"].includes(nav)) return cancel(context); if (session.data.initialMessageId && context.messageId === session.data.initialMessageId) { await flows.updateFlow(...args(context), { data: { ...session.data, initialMessageId: null } }); return { status: "initial_ignored" }; }
    if (nav === "repeat") { await reply(context, session.step === "choose_group" ? groupMenu(session.data.groups) : review(session.data)); return { status: "repeated" }; }
    if (session.step === "choose_group") { const normalized = resolver.normalizeInput(text), index = Number(normalized) - 1, selected = session.data.groups[index] || session.data.groups.find(group => resolver.normalizeInput(group.name) === normalized); if (!selected) { await reply(context, "❌ Escolha um grupo válido."); return { status: "invalid_group" }; } if (await require("./moderationService").isDomainBlacklisted(session.data.link.domain, selected.groupId)) return cancel(context, "🚫 Este domínio não pode ser enviado para análise neste grupo."); const whitelisted = await require("./moderationService").isDomainWhitelisted(session.data.link.domain, selected.groupId); await flows.updateFlow(...args(context), { step: "description_choice", data: { ...session.data, groupId: selected.groupId, groupName: selected.name, whitelisted } }); await reply(context, "Deseja adicionar uma descrição?\n\n1️⃣ Sim\n2️⃣ Não"); return { status: "group_selected" }; }
    if (session.step === "description_choice") { const answer = resolver.resolveYesNo(text); if (answer === null) { await reply(context, "❌ Responda 1 para Sim ou 2 para Não."); return { status: "invalid" }; } if (answer) { await flows.updateFlow(...args(context), { step: "description_text" }); await reply(context, "Envie uma descrição curta, com até 300 caracteres."); } else { const data = { ...session.data, description: "" }; await flows.updateFlow(...args(context), { step: "review", data }); await reply(context, review(data)); } return { status: "description_choice" }; }
    if (session.step === "description_text") { let description; try { description = approval.sanitizeLinkDescription(text); } catch (error) { await reply(context, `❌ ${error.message}`); return { status: "invalid_description" }; } const data = { ...session.data, description }; await flows.updateFlow(...args(context), { step: "review", data }); await reply(context, review(data)); return { status: "review" }; }
    if (session.step === "review") { const choice = resolver.normalizeInput(text); if (choice === "2") { await flows.updateFlow(...args(context), { step: "choose_group" }); await reply(context, groupMenu(session.data.groups)); return { status: "edit_group" }; } if (choice === "3") { await flows.updateFlow(...args(context), { step: "description_choice" }); await reply(context, "Deseja adicionar uma descrição?\n\n1️⃣ Sim\n2️⃣ Não"); return { status: "edit_description" }; } if (choice === "4") return cancel(context); if (choice !== "1") { await reply(context, "❌ Escolha uma opção válida."); return { status: "invalid" }; }
      const result = await approval.createLinkRequest({ groupId: session.data.groupId, requesterId: context.userId, link: session.data.link, description: session.data.description }); await flows.finishFlow(...args(context)); await reply(context, `${result.duplicate ? "ℹ️ Esta solicitação já existe." : "✅ Solicitação enviada para análise."}\n\nProtocolo: ${result.request.requestId}`);
      if (!result.duplicate) { const access = await resolveAccess(context, result.request.groupId, context.userId).catch(() => null), requesterName = await identities.resolveDisplayName(context.userId); await approval.notifyGroupAdmins({ request: result.request, admins: (access?.chat?.participants || []).filter(item => item.isAdmin || item.isSuperAdmin), requesterName, groupName: session.data.groupName, sendPrivate: (id, message) => context.client.sendMessage(typeof id === "string" ? id : id._serialized, message) }); }
      return { status: "created", ...result }; }
    return { status: "ignored" };
  }
  async function handleReview(context, session, text) { const choice = resolver.normalizeInput(text); if (session.step === "review_action") { if (choice === "3" || ["cancel", "back", "menu"].includes(resolver.resolveNavigation(text))) return cancel(context); if (choice === "1") { await flows.updateFlow(...args(context), { step: "confirm_publish" }); await reply(context, "⚠️ Confirmar aprovação e publicação pelo MikaBot?\n\n1️⃣ Confirmar\n2️⃣ Cancelar"); return { status: "confirm_publish" }; } if (choice === "2") { await flows.updateFlow(...args(context), { step: "reject_reason" }); await reply(context, "Informe o motivo da rejeição ou responda 2 para não informar."); return { status: "reject_reason" }; } }
    if (session.step === "confirm_publish") { if (resolver.resolveYesNo(text) !== true) return cancel(context); const request = await approval.getLinkRequestForReview(session.data.requestId); if (!await approval.canApproveLinkRequest({ role: session.data.role, request })) return cancel(context, "❌ Você não possui permissão para aprovar esta solicitação."); const requesterName = await identities.resolveDisplayName(request.requesterId); const result = await approval.publishApprovedLink({ requestId: request.requestId, actorId: context.userId, requesterName, sendToGroup: (groupId, message) => context.client.sendMessage(groupId, message) }); await flows.finishFlow(...args(context)); await reply(context, result.published ? "✅ Link aprovado e publicado pelo MikaBot." : result.duplicate ? "ℹ️ Esta solicitação já foi publicada." : "❌ Não foi possível publicar; a solicitação voltou para pendente."); if (result.published) await approval.notifyRequester({ request: result.request, text: `✅ Seu link foi aprovado e publicado.\n\nProtocolo: ${result.request.requestId}`, sendPrivate: (id, message) => context.client.sendMessage(id, message) }); return { status: "publish_result", result }; }
    if (session.step === "reject_reason") { const reason = resolver.resolveYesNo(text) === false ? "" : approval.sanitizeLinkDescription(text); await flows.updateFlow(...args(context), { step: "confirm_reject", data: { ...session.data, reason } }); await reply(context, "⚠️ Confirmar rejeição?\n\n1️⃣ Confirmar\n2️⃣ Cancelar"); return { status: "confirm_reject" }; }
    if (session.step === "confirm_reject") { if (resolver.resolveYesNo(text) !== true) return cancel(context); const request = await approval.getLinkRequestForReview(session.data.requestId); if (!await approval.canApproveLinkRequest({ role: session.data.role, request })) return cancel(context, "❌ Você não possui permissão para rejeitar esta solicitação."); const rejected = await approval.rejectLinkRequest({ requestId: request.requestId, actorId: context.userId, reason: session.data.reason }); await flows.finishFlow(...args(context)); await reply(context, "✅ Solicitação rejeitada."); await approval.notifyRequester({ request: rejected, text: `❌ LINK NÃO APROVADO\n\nProtocolo: ${rejected.requestId}\nGrupo: ${session.data.names?.groupName || "Grupo"}\nMotivo: ${rejected.reviewReason || "Não informado"}`, sendPrivate: (id, message) => context.client.sendMessage(id, message) }); return { status: "rejected", request: rejected }; }
    await reply(context, "❌ Escolha uma opção válida."); return { status: "invalid" }; }
  async function handleAnswer(context, text) { const session = await flows.getActiveFlow(...args(context)); if (!session) return { status: "ignored" }; if (session.flowId === "link_approval_request") return handleRequest(context, session, text); if (session.flowId === "link_approval_cancel") { if (resolver.resolveYesNo(text) !== true) return cancel(context); const request = await approval.cancelLinkRequest({ requestId: session.data.requestId, requesterId: context.userId }); await flows.finishFlow(...args(context)); await reply(context, `✅ Solicitação ${request.requestId} cancelada.`); return { status: "cancelled_request", request }; } if (session.flowId === "link_approval_review") return handleReview(context, session, text); return { status: "ignored" }; }
  async function handlePotentialPrivateLink(context, text) { if (context.isGroup || String(text || "").trim().startsWith("!")) return false; if (await hasActiveFlow(context)) return false; const links = require("./antiLinkService").extractLinks(text); if (!links.length) return false; await startRequest(context, String(text).trim(), context.messageId); return true; }
  return { startRequest, startCancel, startReview, hasActiveFlow, handleAnswer, handlePotentialPrivateLink, groupMenu, review };
}
const service = createLinkApprovalFlowService();
module.exports = { ...service, createLinkApprovalFlowService };
