"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),fsp=require("fs").promises,os=require("os"),path=require("path");const {createModerationRepository}=require("../src/repositories/moderationRepository");const {createModerationService}=require("../src/services/moderationService");const {createLinkApprovalService}=require("../src/services/linkApprovalService");
async function fixture(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),"link-admin-")),repository=createModerationRepository({dataDir:path.join(root,"mod"),backupRoot:path.join(root,"back")}),moderation=createModerationService({repository}),approval=createLinkApprovalService({repository,moderationService:moderation});await moderation.updateGroupConfig("g@g.us",{settings:{approval:{enabled:true}}});const created=await approval.createLinkRequest({groupId:"g@g.us",requesterId:"u@lid",url:"https://youtube.com/watch",description:"Raid"});return{repository,moderation,approval,request:created.request};}
test("lista pendentes paginados de cinco e solicitações do usuário",async()=>{const f=await fixture();for(let i=0;i<6;i++)await f.approval.createLinkRequest({groupId:"g@g.us",requesterId:"u@lid",url:`https://example.com/${i}`});assert.equal((await f.approval.listPendingGroupRequests({groupId:"g@g.us",page:1})).items.length,5);assert.equal((await f.approval.listRequesterLinkRequests({requesterId:"u@lid",page:2})).items.length,2);});
test("admin e dono analisam; moderador é bloqueado por padrão",async()=>{const f=await fixture();assert.equal(await f.approval.canReviewLinkRequest({role:{isAdmin:true},request:f.request}),true);assert.equal(await f.approval.canReviewLinkRequest({role:{isOwner:true},request:f.request}),true);assert.equal(await f.approval.canReviewLinkRequest({role:{isModerator:true},request:f.request}),false);});
test("pedido inexistente e expirado não podem ser analisados",async()=>{const f=await fixture();await assert.rejects(()=>f.approval.getLinkRequestForReview("LINK-999999"),/não encontrada/i);await f.repository.updatePendingLink(f.request.requestId,{expiresAt:"2000-01-01T00:00:00.000Z"});const expired=await f.approval.getLinkRequestForReview(f.request.requestId);assert.equal(expired.status,"expired");});
test("rejeição aceita motivo opcional, preserva registro e não cria advertência",async()=>{const f=await fixture(),rejected=await f.approval.rejectLinkRequest({requestId:f.request.requestId,actorId:"admin@lid",reason:"Divulgação não permitida"});assert.equal(rejected.status,"rejected");assert.equal(rejected.reviewReason,"Divulgação não permitida");assert.equal(Object.keys((await f.repository.getDatabase()).warnings).length,0);});
test("cancelamento exige o solicitante e somente pendente",async()=>{const f=await fixture();await assert.rejects(()=>f.approval.cancelLinkRequest({requestId:f.request.requestId,requesterId:"other@lid"}),/não pode/);const cancelled=await f.approval.cancelLinkRequest({requestId:f.request.requestId,requesterId:"u@lid"});assert.equal(cancelled.status,"cancelled");await assert.rejects(()=>f.approval.cancelLinkRequest({requestId:f.request.requestId,requesterId:"u@lid"}),/pendentes/);});
test("nova solicitação é permitida após rejeição, cancelamento e expiração",async()=>{const f=await fixture();await f.approval.rejectLinkRequest({requestId:f.request.requestId,actorId:"admin@lid"});const next=await f.approval.createLinkRequest({groupId:"g@g.us",requesterId:"u@lid",url:"https://youtube.com/watch"});assert.notEqual(next.request.requestId,f.request.requestId);});
test("notificação de admins é idempotente e falha não cancela solicitação",async()=>{const f=await fixture();let sends=0;await f.approval.notifyGroupAdmins({request:f.request,admins:[{id:"a@lid",isAdmin:true}],sendPrivate:async()=>{sends++},requesterName:"Nome",groupName:"Grupo"});await f.approval.notifyGroupAdmins({request:f.request,admins:[{id:"a@lid",isAdmin:true}],sendPrivate:async()=>{sends++},requesterName:"Nome",groupName:"Grupo"});await f.approval.notifyGroupAdmins({request:f.request,admins:[{id:"b@lid",isAdmin:true}],sendPrivate:async()=>{throw new Error("falha")},requesterName:"Nome",groupName:"Grupo"});assert.equal(sends,1);assert.equal((await f.repository.listHistory({action:"link_admin_notification_failed"})).total,1);assert.equal((await f.repository.getPendingLink(f.request.requestId)).status,"pending");});
test("comandos administrativos e aliases são registrados",()=>{const commands=require("../src/commands/linkApprovalAdmin");assert.deepEqual(commands.map(c=>c.name),["linkspendentes","analisarlink","aprovarsolicitacao","rejeitarsolicitacao"]);assert.ok(commands[0].aliases.includes("links pendentes"));});
