"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),fsp=require("fs").promises,os=require("os"),path=require("path");
const {createModerationRepository}=require("../src/repositories/moderationRepository");const {createModerationService}=require("../src/services/moderationService");const {createAntiLinkService}=require("../src/services/antiLinkService");const {createLinkApprovalService}=require("../src/services/linkApprovalService");const {createLinkApprovalFlowService}=require("../src/services/linkApprovalFlowService");const {createGuidedFlowService}=require("../src/services/guidedFlowService");
async function fixture(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),"link-request-")),repository=createModerationRepository({dataDir:path.join(root,"mod"),backupRoot:path.join(root,"back")}),moderation=createModerationService({repository}),anti=createAntiLinkService({moderationService:moderation}),directory={listActiveGroups:async()=>[{groupId:"g@g.us",name:"Pokémon GO PB",active:true}],formatGroupDisplayName:g=>g.name},approval=createLinkApprovalService({repository,moderationService:moderation,antiLinkService:anti,groupDirectoryService:directory}),guided=createGuidedFlowService({filePath:path.join(root,"flows.json")}),flow=createLinkApprovalFlowService({guidedFlowService:guided,linkApprovalService:approval});return{root,repository,moderation,anti,approval,flow,guided,directory};}
test("aprovação fica desativada por padrão e ativação é isolada por grupo",async()=>{const f=await fixture();assert.equal(f.moderation.getDefaultGroupConfig().settings.approval.enabled,false);await f.moderation.updateGroupConfig("g@g.us",{settings:{approval:{enabled:true}}});assert.equal((await f.moderation.getGroupConfig("g@g.us")).settings.approval.enabled,true);assert.equal(await f.moderation.getGroupConfig("other@g.us"),null);});
test("valida HTTP/HTTPS, sanitiza query e fragmento e gera hash",async()=>{const f=await fixture(),link=f.approval.validateLinkRequest("https://youtube.com/watch?v=SEGREDO#x");assert.equal(link.domain,"youtube.com");assert.equal(link.linkType,"youtube");assert.equal(link.sanitizedUrl,"https://youtube.com/watch");assert.equal(link.urlHash.length,64);assert.doesNotMatch(link.sanitizedUrl,/SEGREDO|#|\?/);});
test("rejeita protocolo perigoso, credenciais, URL inválida e múltiplos links",async()=>{const f=await fixture();for(const value of ["javascript:alert(1)","data:text/plain,x","file:///tmp/x","https://user:pass@example.com/x","texto comum","https://a.com https://b.com"])assert.throws(()=>f.approval.validateLinkRequest(value));});
test("lista apenas grupos elegíveis com membro, bot e aprovação ativa",async()=>{const f=await fixture();await f.moderation.updateGroupConfig("g@g.us",{settings:{approval:{enabled:true}}});let groups=await f.approval.getEligibleGroupsForLinkRequest({requesterId:"u@lid",resolveAccess:async()=>({userPresent:true,botPresent:true})});assert.equal(groups.length,1);groups=await f.approval.getEligibleGroupsForLinkRequest({requesterId:"u@lid",resolveAccess:async()=>({userPresent:false,botPresent:true})});assert.equal(groups.length,0);});
test("descrição é opcional e recusa link, telefone, ID, comando e excesso",async()=>{const f=await fixture();assert.equal(f.approval.sanitizeLinkDescription("  Dicas para Raid  "),"Dicas para Raid");for(const value of ["https://x.com","+55 83 99999-9999","abc@lid","!banir","x".repeat(301)])assert.throws(()=>f.approval.sanitizeLinkDescription(value));});
test("cria protocolo e reutiliza duplicidade ativa",async()=>{const f=await fixture();await f.moderation.updateGroupConfig("g@g.us",{settings:{approval:{enabled:true}}});const input={groupId:"g@g.us",requesterId:"u@lid",url:"https://youtube.com/watch?v=1",description:"Raid"},one=await f.approval.createLinkRequest(input),two=await f.approval.createLinkRequest(input);assert.match(one.request.requestId,/^LINK-\d{6}$/);assert.equal(two.duplicate,true);assert.equal(two.request.requestId,one.request.requestId);assert.equal(Object.keys((await f.repository.getDatabase()).pendingLinks).length,1);});
test("blacklist bloqueia e whitelist apenas informa",async()=>{const f=await fixture();await f.moderation.updateGroupConfig("g@g.us",{settings:{approval:{enabled:true}}});await f.repository.addDomainRule("blacklist","evil.com",{scope:"group",groupId:"g@g.us"});await assert.rejects(()=>f.approval.createLinkRequest({groupId:"g@g.us",requesterId:"u@lid",url:"https://evil.com"}),/não pode/);await f.repository.addDomainRule("whitelist","youtube.com",{scope:"group",groupId:"g@g.us"});const result=await f.approval.createLinkRequest({groupId:"g@g.us",requesterId:"u@lid",url:"https://youtube.com/watch"});assert.equal(result.request.status,"pending");});
test("fluxo privado escolhe grupo, descrição, revisa e persiste somente ao confirmar",async()=>{const f=await fixture();await f.moderation.updateGroupConfig("g@g.us",{settings:{approval:{enabled:true}}});const replies=[],client={info:{wid:"bot@lid"},getChatById:async()=>({participants:[{id:"u@lid"},{id:"bot@lid",isAdmin:true}]}),sendMessage:async()=>({})},context={platform:"whatsapp",groupId:"u@c.us",userId:"u@lid",messageId:"M1",isGroup:false,client,replyText:async t=>replies.push(t)};await f.flow.startRequest(context,"https://youtube.com/watch","M1");await f.flow.handleAnswer(context,"1");await f.flow.handleAnswer(context,"1");await f.flow.handleAnswer(context,"não");assert.equal(Object.keys((await f.repository.getDatabase()).pendingLinks).length,0);await f.flow.handleAnswer(context,"1");assert.equal(Object.keys((await f.repository.getDatabase()).pendingLinks).length,1);assert.match(replies.join(" "),/Protocolo/);});
test("cancelamento antes da revisão não cria protocolo e nenhum grupo é amigável",async()=>{const f=await fixture(),replies=[],context={platform:"whatsapp",groupId:"u@c.us",userId:"u@lid",isGroup:false,messageId:"M",client:{info:{wid:"bot@lid"},getChatById:async()=>({participants:[]})},replyText:async t=>replies.push(t)};assert.equal((await f.flow.startRequest(context,"https://youtube.com","M")).status,"no_groups");assert.equal(Object.keys((await f.repository.getDatabase()).pendingLinks).length,0);});
test("comandos e aliases do membro permanecem privados",()=>{const commands=require("../src/commands/linkApprovalRequest");assert.deepEqual(commands.map(c=>c.name),["enviarlink","meuslinks","cancelarlink"]);assert.ok(commands[0].aliases.includes("aprovarlink"));assert.ok(commands[1].aliases.includes("links enviados"));});
