"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),fsp=require("fs").promises,os=require("os"),path=require("path");const {createModerationRepository}=require("../src/repositories/moderationRepository");const {createModerationService}=require("../src/services/moderationService");const {createLinkApprovalService}=require("../src/services/linkApprovalService");const {createAntiLinkService}=require("../src/services/antiLinkService");
async function fixture(){const root=await fsp.mkdtemp(path.join(os.tmpdir(),"link-publish-")),repository=createModerationRepository({dataDir:path.join(root,"mod"),backupRoot:path.join(root,"back")}),moderation=createModerationService({repository}),approval=createLinkApprovalService({repository,moderationService:moderation});await moderation.updateGroupConfig("g@g.us",{settings:{approval:{enabled:true},antiLink:{enabled:true}}});const request=(await approval.createLinkRequest({groupId:"g@g.us",requesterId:"u@lid",url:"https://youtube.com/watch?v=secret",description:"Raid"})).request;return{repository,moderation,approval,request};}
test("publicação usa reserva atômica e dupla aprovação publica uma vez",async()=>{const f=await fixture();let sends=0;const send=async()=>{sends++;await new Promise(r=>setTimeout(r,20));return{id:{_serialized:"MSG"}}};const [a,b]=await Promise.all([f.approval.publishApprovedLink({requestId:f.request.requestId,actorId:"a@lid",sendToGroup:send,requesterName:"Nome"}),f.approval.publishApprovedLink({requestId:f.request.requestId,actorId:"a@lid",sendToGroup:send,requesterName:"Nome"})]);assert.equal(sends,1);assert.equal([a,b].filter(x=>x.published).length,1);assert.equal((await f.repository.getPendingLink(f.request.requestId)).status,"published");});
test("falha de publicação desfaz reserva e permite nova tentativa",async()=>{const f=await fixture(),failed=await f.approval.publishApprovedLink({requestId:f.request.requestId,actorId:"a@lid",sendToGroup:async()=>{throw new Error("fail")}});assert.equal(failed.failureCode,"send_failed");assert.equal((await f.repository.getPendingLink(f.request.requestId)).status,"pending");const success=await f.approval.publishApprovedLink({requestId:f.request.requestId,actorId:"a@lid",sendToGroup:async()=>({id:"OK"}),requesterName:"Nome"});assert.equal(success.published,true);});
test("mensagem publicada contém somente URL sanitizada e dados públicos",async()=>{const f=await fixture(),message=f.approval.formatPublishedLinkMessage(f.request,"Nome");assert.match(message,/https:\/\/youtube\.com\/watch/);assert.doesNotMatch(message,/secret|requesterId|@lid|LINK-|urlHash/);});
test("mensagem do próprio MikaBot é autorizada pelo Antilink",async()=>{const f=await fixture(),anti=createAntiLinkService({moderationService:f.moderation}),msg={from:"g@g.us",fromMe:true,body:f.request.sanitizedUrl};assert.equal((await anti.inspectMessage(msg)).status,"ignored");});
test("histórico não contém query, token, URL completa ou corpo",async()=>{const f=await fixture();await f.approval.publishApprovedLink({requestId:f.request.requestId,actorId:"a@lid",sendToGroup:async()=>({id:"OK"}),requesterName:"Nome"});const raw=JSON.stringify(await f.repository.getDatabase());const history=JSON.stringify((await f.repository.getDatabase()).history);assert.doesNotMatch(history,/secret|https:\/\//);assert.match(raw,/sanitizedUrl/);});
test("nenhum listener, rede, preview ou polling foi criado",async()=>{for(const file of ["linkApprovalService.js","linkApprovalFlowService.js"]){const source=await fsp.readFile(path.join(__dirname,"..","src","services",file),"utf8");assert.doesNotMatch(source,/client\.on|setInterval|fetch\(|axios|https\.get|http\.get|puppeteer/);}});
