"use strict";
const assert = require("node:assert/strict");
const test = require("node:test");
const fsp = require("fs").promises, os = require("os"), path = require("path");
const { createModerationRepository } = require("../src/repositories/moderationRepository");
const { createModerationService } = require("../src/services/moderationService");
const { createAntiLinkService } = require("../src/services/antiLinkService");
const antiLinkCommandModule = require("../src/commands/moderationAntiLink");

async function fixture(patch = {}) {
  const root = await fsp.mkdtemp(path.join(os.tmpdir(), "mikabot-antilink-")); const repository = createModerationRepository({ dataDir: path.join(root, "data"), backupRoot: path.join(root, "backups") }); const moderation = createModerationService({ repository }); const service = createAntiLinkService({ moderationService: moderation });
  const groupId = "group@g.us", member = { id: "member@lid", isAdmin: false, isSuperAdmin: false }, admin = { id: "admin@lid", isAdmin: true, isSuperAdmin: false }, owner = { id: "owner@lid", isAdmin: true, isSuperAdmin: true }, bot = { id: "bot@lid", isAdmin: true, isSuperAdmin: false };
  await moderation.updateGroupConfig(groupId, patch);
  function msg(body, options = {}) { const state = { deleted: 0, deleteArgs: [], replies: [], removed: [] }; const participants = options.participants || [member, admin, owner, bot]; const chat = { isGroup: true, participants, removeParticipants: async ids => { if (options.removeFails) throw new Error("fail"); state.removed.push(...ids); } }; const rawId = options.messageId || `MSG-${Math.random()}`, id = options.idWithoutSerialized ? { toString: () => rawId } : { _serialized: rawId }; return { from: groupId, author: options.author || member.id, body, caption: options.caption, timestamp: options.timestamp, id, _client: { info: { wid: bot.id } }, getChat: async () => { if (options.chatFails) throw new Error("fail"); return chat; }, delete: async everyone => { state.deleteArgs.push(everyone); if (options.deleteFails) throw new Error(options.deleteError || "fail"); state.deleted += 1; }, reply: async text => state.replies.push(text), state, chat }; }
  return { repository, moderation, service, msg, groupId, member, admin, owner, bot };
}

test("Antilink permanece desativado por padrão e isolado por grupo", async () => { const f = await fixture(); assert.equal((await f.service.inspectMessage(f.msg("https://evil.example"))).status, "disabled"); assert.equal((await f.repository.getDatabase()).revision, 1); });
test("detecta HTTP, HTTPS, www, domínio sem protocolo e legenda", async () => { const f = await fixture({ settings: { antiLink: { enabled: true } } }); for (const text of ["http://evil.example/x", "https://evil.example", "www.evil.example", "evil.example/test"]) assert.equal(f.service.extractLinks(text).length, 1); const m = f.msg("", { caption: "veja https://evil.example" }); assert.equal((await f.service.inspectMessage(m)).status, "blocked"); });
test("ignora texto comum, versão, horário, Friend Code, coordenada, arquivo e email", async () => { const f = await fixture(); for (const text of ["Olá. tudo bem", "v2.1.0", "20:30", "1234 5678 9012", "-23.5505,-46.6333", "relatorio.pdf", "a@b.com"]) assert.deepEqual(f.service.extractLinks(text), []); });
test("classifica serviços conhecidos e não confia em domínio parcial", async () => { const f = await fixture(); assert.equal(f.moderation.classifyLink("youtube.com/watch/x"), "youtube"); assert.equal(f.moderation.classifyLink("youtube.com.evil.example"), "other"); assert.equal(f.moderation.classifyLink("chat.whatsapp.com/abc"), "whatsapp"); assert.equal(f.moderation.classifyLink("discord.gg/x"), "discord"); assert.equal(f.moderation.classifyLink("bit.ly/x"), "shortened"); });
test("whitelist global e por grupo liberam, blacklist tem prioridade", async () => { const f = await fixture({ settings: { antiLink: { enabled: true } } }); await f.repository.addDomainRule("whitelist", "youtube.com", { scope: "global" }); assert.equal((await f.service.inspectMessage(f.msg("https://sub.youtube.com/x"))).status, "allowed"); await f.repository.addDomainRule("whitelist", "safe.example", { scope: "group", groupId: f.groupId }); assert.equal((await f.service.inspectMessage(f.msg("safe.example"))).status, "allowed"); await f.repository.addDomainRule("blacklist", "safe.example", { scope: "group", groupId: f.groupId }); assert.equal((await f.service.inspectMessage(f.msg("safe.example"))).status, "blocked"); });
test("admin tem bypass; sem bypass apaga mas não adverte; moderador comum não tem bypass", async () => { let f = await fixture({ settings: { antiLink: { enabled: true } } }); assert.equal((await f.service.inspectMessage(f.msg("evil.example", { author: f.admin.id }))).status, "allowed"); f = await fixture({ settings: { antiLink: { enabled: true, adminsBypass: false } } }); const result = await f.service.inspectMessage(f.msg("evil.example", { author: f.admin.id })); assert.equal(result.deletion.deleted, true); assert.equal(result.warning, null); });
test("dono e bot são protegidos; identidade incerta falha com segurança", async () => { const f = await fixture({ settings: { antiLink: { enabled: true, adminsBypass: false } } }); assert.equal((await f.service.inspectMessage(f.msg("evil.example", { author: f.owner.id }))).warning, null); assert.equal((await f.service.inspectMessage(f.msg("evil.example", { author: f.bot.id }))).status, "allowed"); assert.equal((await f.service.inspectMessage(f.msg("evil.example", { author: "missing@lid" }))).status, "safe_failure"); });
test("exclusão real distingue sucesso e falha", async () => { const f = await fixture({ settings: { antiLink: { enabled: true } } }); const ok = f.msg("evil.example", { messageId: "D1" }); assert.equal((await f.service.inspectMessage(ok)).deletion.deleted, true); const fail = f.msg("evil.example", { messageId: "D2", deleteFails: true }); const result = await f.service.inspectMessage(fail); assert.equal(result.deletion.deleted, false); assert.match(fail.state.replies[0], /Não consegui remover/); });
test("exclusão para todos usa delete(true) e recompõe id serializado", async () => { const f = await fixture({ settings: { antiLink: { enabled: true } } }); const message = f.msg("evil.example", { messageId: "D-SERIAL", idWithoutSerialized: true }); const result = await f.service.inspectMessage(message); assert.equal(result.deletion.deleted, true); assert.deepEqual(message.state.deleteArgs, [true]); assert.equal(message.id._serialized, "D-SERIAL"); });
test("diagnóstico de exclusão sanitiza erro e não expõe URL ou IDs", async () => { const f = await fixture({ settings: { antiLink: { enabled: true } } }); const logs = [], original = console.log; console.log = line => logs.push(String(line)); try { await f.service.handleIncomingMessage({ isGroup: true, message: f.msg("evil.example", { deleteFails: true, deleteError: "falha https://segredo.example 5511999999999 user@lid" }) }); } finally { console.log = original; } const text = logs.join("\n"); assert.match(text, /\[DELETE\] attempt=delete_everyone/); assert.match(text, /\[DELETE\] success=false/); assert.doesNotMatch(text, /segredo\.example|5511999999999|user@lid|@g\.us|@c\.us/); });
test("mensagem antiga não é declarada removida quando revogação não está disponível", async () => { const f = await fixture({ settings: { antiLink: { enabled: true } } }); const message = f.msg("evil.example", { timestamp: Math.floor(Date.now() / 1000) - 90000 }); message._client.pupPage = { evaluate: async () => false }; const result = await f.service.inspectMessage(message); assert.equal(result.deletion.deleted, false); assert.equal(result.deletion.failureCode, "revoke_unavailable"); assert.equal(message.state.deleted, 0); });
test("advertência automática é idempotente e cruza o limite uma vez", async () => { const f = await fixture({ settings: { antiLink: { enabled: true }, warnings: { enabled: true, limit: 3, finalAction: "notify_admins" } } }); for (const id of ["W1", "W2", "W3"]) await f.service.inspectMessage(f.msg("evil.example", { messageId: id })); await f.service.inspectMessage(f.msg("evil.example", { messageId: "W3" })); assert.equal(await f.moderation.getWarningCount(f.groupId, f.member.id), 3); assert.equal((await f.repository.listHistory({ action: "warning_limit_reached" })).total, 1); });
test("remove_member remove somente ao cruzar limite e com bot admin", async () => { const f = await fixture({ settings: { antiLink: { enabled: true }, warnings: { enabled: true, limit: 1, finalAction: "remove_member" } } }); const m = f.msg("evil.example", { messageId: "R1" }); const result = await f.service.inspectMessage(m); assert.equal(result.final.removed, true); assert.equal(m.state.removed.length, 1); });
test("sem permissão do bot registra falha e mantém advertência", async () => { const f = await fixture({ settings: { antiLink: { enabled: true }, warnings: { enabled: true, limit: 1, finalAction: "remove_member" } } }); const participants = [f.member, { ...f.bot, isAdmin: false }]; const result = await f.service.inspectMessage(f.msg("evil.example", { messageId: "NP", participants })); assert.equal(result.final.removed, false); assert.equal(await f.moderation.getWarningCount(f.groupId, f.member.id), 1); });
test("ban_and_remove configurado antes do limite dispara em 3/3 e não repete em 4/3 ou 5/3", async () => { const f = await fixture({ settings: { antiLink: { enabled: true }, warnings: { enabled: true, limit: 3, finalAction: "ban_and_remove" }, ban: { enabled: true, blockReentry: true } } }); const results = []; for (let i = 1; i <= 5; i++) results.push(await f.service.inspectMessage(f.msg("evil.example", { messageId: `B${i}`, deleteFails: i === 3 }))); assert.equal(results[0].final, null); assert.equal(results[1].final, null); assert.equal(results[2].final.action, "ban_and_remove"); assert.equal(results[2].final.removed, true); assert.equal(results[3].final, null); assert.equal(results[4].final, null); assert.equal(await f.repository.countActiveBans(f.groupId), 1); assert.equal((await f.repository.listHistory({ action: "member_removed" })).total, 1); assert.match(results[4].warning.activeCount >= results[4].warning.limit ? "limite já atingido" : "", /limite já atingido/); });
test("histórico guarda domínio, nunca URL, query ou corpo", async () => { const f = await fixture({ settings: { antiLink: { enabled: true } } }); await f.service.inspectMessage(f.msg("https://evil.example/private/path?token=SEGREDO", { messageId: "H1" })); const raw = JSON.stringify(await f.repository.getDatabase()); assert.doesNotMatch(raw, /SEGREDO|private\/path|https:\/\//); assert.match(raw, /evil\.example/); });
test("não cria listener, polling, HTTP ou redirecionamento", async () => { const source = await fsp.readFile(path.join(__dirname, "..", "src", "services", "antiLinkService.js"), "utf8"); assert.doesNotMatch(source, /client\.on|setInterval|fetch\(|axios|https\.get|http\.get/); });
test("comandos administrativos configuram somente o grupo e recusam valores inválidos", async () => { const updates=[], replies=[], commands=antiLinkCommandModule.createModerationAntiLinkCommands({moderationService:{updateGroupConfig:async(group,patch)=>updates.push({group,patch})}}), loader={chat:{isGroup:true},role:{isAdmin:true}}, msg={from:"g@g.us",reply:async text=>replies.push(text)}; await commands[0].execute(null,msg,["on"],loader); assert.equal(updates[0].group,"g@g.us"); assert.equal(updates[0].patch.settings.antiLink.enabled,true); await commands[2].execute(null,msg,["zero"],loader); assert.equal(updates.length,1); assert.match(replies.at(-1),/inteiro/); });
