"use strict";
const assert = require("node:assert/strict"); const test = require("node:test"); const fsp = require("fs").promises, os = require("os"), path = require("path");
const { createModerationRepository } = require("../src/repositories/moderationRepository"); const { createModerationService } = require("../src/services/moderationService"); const { createModerationBanFlowService } = require("../src/services/moderationBanFlowService"); const { createGuidedFlowService } = require("../src/services/guidedFlowService");
const banCommandModule = require("../src/commands/moderationBans");
async function fixture() { const root = await fsp.mkdtemp(path.join(os.tmpdir(), "mikabot-bans-")), repository = createModerationRepository({ dataDir: path.join(root,"mod"), backupRoot: path.join(root,"back") }), moderation = createModerationService({ repository }), flows = createGuidedFlowService({ filePath: path.join(root,"flows.json") }), flow = createModerationBanFlowService({ guidedFlowService: flows, moderationService: moderation }); return { root, repository, moderation, flow }; }
test("ban é lógico, idempotente e usa o mesmo banco", async () => { const f=await fixture(), input={groupId:"g@g.us",targetId:"u@lid",actorId:"bot@lid",receiptId:"B1",metadata:{warningCount:3,warningLimit:3}}; const one=await f.moderation.banPlayer(input), two=await f.moderation.banPlayer(input); assert.equal(one.duplicate,false); assert.equal(two.duplicate,true); assert.equal(await f.repository.countActiveBans("g@g.us"),1); assert.equal((await f.repository.getDatabase()).bans[one.ban.banId].active,true); });
test("lista banimentos ativos com paginação de cinco", async () => { const f=await fixture(); for(let i=0;i<7;i++) await f.moderation.banPlayer({groupId:"g@g.us",targetId:`u${i}@lid`,actorId:"bot@lid",receiptId:`B${i}`}); const page=await f.moderation.listBannedPlayers({groupId:"g@g.us",page:2}); assert.equal(page.items.length,2); assert.equal(page.totalPages,2); });
test("desbanir preserva registro e cria histórico", async () => { const f=await fixture(), stored=await f.moderation.banPlayer({groupId:"g@g.us",targetId:"u@lid",actorId:"bot@lid",receiptId:"B"}); const revoked=await f.moderation.unbanPlayer({banId:stored.ban.banId,actorId:"admin@lid"}); assert.equal(revoked.active,false); assert.ok(revoked.revokedAt); assert.equal((await f.repository.listHistory({action:"ban_revoked"})).total,1); });
test("fluxo guiado confirma e cancela via resolvedor central", async () => { const f=await fixture(), stored=await f.moderation.banPlayer({groupId:"g@g.us",targetId:"u@lid",actorId:"bot@lid",receiptId:"B"}), replies=[], context={platform:"whatsapp",groupId:"g@g.us",userId:"admin@lid",isGroup:true,replyText:async t=>replies.push(t)}; await f.flow.startConfirmation(context,{banId:stored.ban.banId,name:"Treinador"}); await f.flow.handleAnswer(context,"sim"); assert.equal(await f.moderation.isPlayerBanned("g@g.us","u@lid"),false); const second=await f.moderation.banPlayer({groupId:"g@g.us",targetId:"v@lid",actorId:"bot@lid",receiptId:"C"}); await f.flow.startConfirmation(context,{banId:second.ban.banId,name:"Outro"}); await f.flow.handleAnswer(context,"cancelar"); assert.equal(await f.moderation.isPlayerBanned("g@g.us","v@lid"),true); });
test("seleção da lista nunca precisa expor identificador", async () => { const f=await fixture(), stored=await f.moderation.banPlayer({groupId:"g@g.us",targetId:"u@lid",actorId:"bot@lid",receiptId:"B"}), replies=[], context={platform:"whatsapp",groupId:"g@g.us",userId:"admin@lid",isGroup:true,replyText:async t=>replies.push(t)}; await f.flow.startList(context,[{banId:stored.ban.banId,name:"Membro"}]); await f.flow.handleAnswer(context,"1"); assert.match(replies[0],/Membro/); assert.doesNotMatch(replies[0],/BAN-|@lid|@g\.us/); });
test("ban_and_remove exige configuração explícita", async () => { const f=await fixture(); await f.moderation.updateGroupConfig("g@g.us",{settings:{warnings:{enabled:true,limit:1,finalAction:"ban_and_remove"}}}); const participant={id:"u@lid",isAdmin:false}, bot={id:"bot@lid",isAdmin:true}, chat={removeParticipants:async()=>{}}; const input={groupId:"g@g.us",targetId:"u@lid",actorId:"bot@lid",botId:"bot@lid",targetParticipant:participant,botParticipant:bot,chat,crossedLimit:true,warningCount:1,warningLimit:1}; const disabled=await f.moderation.applyWarningFinalAction({...input,receiptId:"X"}); assert.equal(disabled.failureCode,"ban_disabled"); assert.equal(await f.moderation.isPlayerBanned("g@g.us","u@lid"),false); await f.moderation.updateGroupConfig("g@g.us",{settings:{ban:{enabled:true}}}); const enabled=await f.moderation.applyWarningFinalAction({...input,receiptId:"Y"}); assert.equal(enabled.removed,true); assert.equal(await f.moderation.isPlayerBanned("g@g.us","u@lid"),true); });
test("reentrada fica preparada e respeita padrão desativado", async () => { const f=await fixture(); await f.moderation.banPlayer({groupId:"g@g.us",targetId:"u@lid",actorId:"bot@lid",receiptId:"B"}); assert.deepEqual(await f.moderation.handleBannedParticipantJoin({groupId:"g@g.us",targetId:"u@lid"}),{blocked:false}); });
test("banco e respostas não exigem telefone nem IDs digitados", async () => { const source=await fsp.readFile(path.join(__dirname,"..","src","commands","moderationBans.js"),"utf8"); assert.match(source,/Membro não identificado|resolveDisplayName/); assert.doesNotMatch(source,/split\("@"\)\[0\]/); });
test("comandos e aliases de banimento são registrados", () => { assert.deepEqual(banCommandModule.map(command=>command.name),["banidos","desbanir grupo"]); assert.deepEqual(banCommandModule[0].aliases,["bans","listaban"]); assert.deepEqual(banCommandModule[1].aliases,["unban","removerban"]); });
test("!banidos restringe grupo e permissão sem expor IDs", async () => { const replies=[], commands=banCommandModule.createModerationBanCommands({ moderationService:{listBannedPlayers:async()=>({items:[],total:0,page:1,totalPages:1})} }), command=commands[0], msg={from:"private@c.us",reply:async text=>replies.push(text)}; await command.execute(null,msg,[],{chat:{isGroup:false},role:{}}); assert.equal(replies[0],"⚠️ Este comando funciona somente em grupos."); msg.from="g@g.us"; await command.execute(null,msg,[],{chat:{isGroup:true},role:{}}); assert.match(replies[1],/permissão/); assert.doesNotMatch(replies.join(" "),/@lid|@g\.us|BAN-/); });
