"use strict";
const approvalDefault = require("../services/linkApprovalService"); const flowDefault = require("../services/linkApprovalFlowService"); const groupsDefault = require("../services/groupDirectoryService"); const identitiesDefault = require("../services/identityService");
const { isGroupMessage } = require("../utils/messageContext");
function createLinkApprovalAdminCommands(options = {}) {
  const approval = options.linkApprovalService || approvalDefault, flow = options.flowService || flowDefault, groups = options.groupDirectoryService || groupsDefault, identities = options.identityService || identitiesDefault;
  const ctx = (client,msg,loader,role=loader.role,isGroup=false) => ({platform:"whatsapp",groupId:msg.from,userId:loader.identity?.id||identities.normalizeUserId(msg.author||msg.from),messageId:msg.id?._serialized||msg.id?.id,isGroup,client,role,replyText:text=>msg.reply(text)});
  async function access(client, groupId, userId) { const chat=await client.getChatById(groupId), participant=chat.participants?.find(item=>identities.identitiesMatch(item.id,userId)); return {chat,participant,role:{isOwner:Boolean(participant?.isSuperAdmin),isAdmin:Boolean(participant?.isAdmin),isModerator:false}}; }
  async function managedGroups(client,userId) { const listed=await groups.listActiveGroups("whatsapp"), result=[]; for(const group of listed){try{const a=await access(client,group.groupId,userId);if(a.participant?.isAdmin||a.participant?.isSuperAdmin)result.push({...group,...a});}catch(_){}} return result; }
  async function resolveGroup(client,msg,args,loader){if(await isGroupMessage(msg,loader.chat))return {groupId:msg.from,name:loader.chat?.name||"Grupo",role:loader.role};const userId=identities.normalizeUserId(msg.from),managed=await managedGroups(client,userId);if(!managed.length)return null;if(managed.length===1)return {groupId:managed[0].groupId,name:groups.formatGroupDisplayName(managed[0]),role:managed[0].role};const index=Number(args[0])-1;if(managed[index])return {groupId:managed[index].groupId,name:groups.formatGroupDisplayName(managed[index]),role:managed[index].role};await msg.reply(`🔗 ESCOLHA O GRUPO\n\n${managed.map((g,i)=>`${i+1}️⃣ ${groups.formatGroupDisplayName(g)}`).join("\n")}\n\nUse !linkspendentes número.`);return null;}
  async function pending(client,msg,args,loader){const selected=await resolveGroup(client,msg,args,loader);if(!selected)return;const role=selected.role;if(!(role?.isOwner||role?.isAdmin||role?.isModerator))return msg.reply("❌ Você não possui permissão para consultar solicitações.");const page=Number(args.at(-1))||1,result=await approval.listPendingGroupRequests({groupId:selected.groupId,page});if(!result.total)return msg.reply("✅ Não há links pendentes neste grupo.");const named=[];for(const item of result.items)named.push({...item,name:await identities.resolveDisplayName(item.requesterId)});return msg.reply(`🔗 LINKS PENDENTES\n\n${named.map((item,i)=>`${i+1}. ${item.requestId}\n   Solicitante: ${item.name}\n   Domínio: ${item.domain}\n   Tipo: ${item.linkType}\n   Criado: ${new Date(item.createdAt).toLocaleDateString("pt-BR")}`).join("\n\n")}\n\nPágina ${result.page} de ${result.totalPages}`);}
  async function analyze(client,msg,args,loader){const inGroup=await isGroupMessage(msg,loader.chat),id=String(args[0]||"").toUpperCase();if(!/^LINK-\d{6}$/.test(id))return msg.reply("Informe um protocolo válido.");const request=await approval.getLinkRequestForReview(id).catch(()=>null);if(!request)return msg.reply("Solicitação não encontrada.");const a=await access(client,request.groupId,ctx(client,msg,loader,loader.role,inGroup).userId).catch(()=>null),role=inGroup?loader.role:a?.role;if(!await approval.canReviewLinkRequest({role,request}))return msg.reply("❌ Você não possui permissão para analisar esta solicitação.");if(inGroup)return msg.reply(`🔗 Solicitação ${request.requestId} pronta para análise. Por privacidade, use este comando no privado do MikaBot.`);const group=await groups.getGroup("whatsapp",request.groupId),requesterName=await identities.resolveDisplayName(request.requesterId);await require("../services/moderationService").registerHistory({groupId:request.groupId,userId:request.requesterId,actorId:ctx(client,msg,loader).userId,action:"link_review_opened",domain:request.domain,metadata:{requestStatus:request.status}});return flow.startReview(ctx(client,msg,loader,role),request,role,{requesterName,groupName:groups.formatGroupDisplayName(group)});}
  async function approve(client,msg,args,loader){return analyze(client,msg,args,loader);}
  async function reject(client,msg,args,loader){return analyze(client,msg,args,loader);}
  return [{name:"linkspendentes",aliases:["links pendentes","pendenteslink"],permissions:true,execute:pending},{name:"analisarlink",aliases:["revisarlink"],permissions:true,execute:analyze},{name:"aprovarsolicitacao",aliases:["aprovarpedido"],permissions:true,execute:approve},{name:"rejeitarsolicitacao",aliases:["rejeitarpedido"],permissions:true,execute:reject}];
}
module.exports=createLinkApprovalAdminCommands();module.exports.createLinkApprovalAdminCommands=createLinkApprovalAdminCommands;
